version: '3'
services:
  db:
    tty: true
    image: postgres:9.5
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres

  frontend:
    build: frontend
    ports:
     - "3000:3000"
    volumes:
     - "./frontend/src:/usr/src/app/src"

  api:
    tty: true
    build: api/
    ports:
     - "8888:8888"
    volumes:
     - "./api:/usr/src/app/"
    links:
     - db

  nginx:
    build: nginx
    ports:
     - "8080:80"
    links:
     - frontend
     - api
